<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>replication-slippage-poly-t-tracts</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="2026-08-11-replication-slippage-poly-T-tracts_files/libs/clipboard/clipboard.min.js"></script>
<script src="2026-08-11-replication-slippage-poly-T-tracts_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="2026-08-11-replication-slippage-poly-T-tracts_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="2026-08-11-replication-slippage-poly-T-tracts_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="2026-08-11-replication-slippage-poly-T-tracts_files/libs/quarto-html/popper.min.js"></script>
<script src="2026-08-11-replication-slippage-poly-T-tracts_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="2026-08-11-replication-slippage-poly-T-tracts_files/libs/quarto-html/anchor.min.js"></script>
<link href="2026-08-11-replication-slippage-poly-T-tracts_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2026-08-11-replication-slippage-poly-T-tracts_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="2026-08-11-replication-slippage-poly-T-tracts_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="2026-08-11-replication-slippage-poly-T-tracts_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="2026-08-11-replication-slippage-poly-T-tracts_files/libs/bootstrap/bootstrap-a80d6bf78715921a7d1a4da328c3e0aa.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="replication-slippage-at-homopolymer-tracts-insertions-vs-deletions-of-t-and-at-vs-gc" class="level1">
<h1>Replication slippage at homopolymer tracts: insertions vs deletions of T, and A/T vs G/C</h1>
<p>Date: 2026-08-11</p>
<section id="q1.-can-slippage-produce-both-insertions-and-deletions-of-t-in-poly-t-tracts" class="level2">
<h2 class="anchored" data-anchor-id="q1.-can-slippage-produce-both-insertions-and-deletions-of-t-in-poly-t-tracts">Q1. Can slippage produce both insertions and deletions of T in poly-T tracts?</h2>
<p>Yes, and this is one of the better-supported facts in the field. The two directions are separate signatures with separate proposed mechanisms.</p>
<ul>
<li><p><strong>COSMIC ID1</strong> = 1 bp <strong>insertion</strong> of T at poly-T. Proposed aetiology: “slippage during DNA replication of the replicated (nascent) DNA strand.” https://cancer.sanger.ac.uk/signatures/id/id1/</p></li>
<li><p><strong>COSMIC ID2</strong> = 1 bp <strong>deletion</strong> of T at poly-T. Proposed aetiology: “slippage during DNA replication of the template DNA strand.” https://cancer.sanger.ac.uk/signatures/id/id2/</p>
<p>Both were extracted in Alexandrov LB et al.&nbsp;(2020) “The repertoire of mutational signatures in human cancer,” <em>Nature</em> 578:94-101. https://www.nature.com/articles/s41586-020-1943-3 , doi:10.1038/s41586-020-1943-3</p>
<p>The mechanistic logic: a loop-out on the <strong>nascent</strong> strand leaves an extra base in the product (insertion), a loop-out on the <strong>template</strong> strand skips a base (deletion). Same slippage event, opposite strand, opposite sign.</p></li>
<li><p>Koh G et al.&nbsp;(2025) “A redefined InDel taxonomy provides insights into mutational signatures,” <em>Nature Genetics</em> 57:1132-1141. https://www.nature.com/articles/s41588-025-02152-y , doi:10.1038/s41588-025-02152-y Experimentally separates the two directions: MMR-deficient lines are dominated by 1 bp T <strong>deletions</strong> at poly-T6+, while polymerase-dysfunction lines give <strong>exclusively</strong> 1 bp T <strong>insertions</strong> at poly-T5+. Note the tract-length split: insertion excess peaks at 5-7 bp, deletion excess grows with longer tracts. They attribute this to proofreading acting only within ~5-7 bp of the active site.</p></li>
<li><p>Germline confirmation in a real pedigree: Happ HC, Sasani TA, Warner D, Neklason DW, Quinlan AR (2026) “AVITI sequencing of a four-generation CEPH/Utah pedigree confirms low mutation rates at homopolymer loci despite their low sequence complexity,” <em>Genome Biology</em> 27:215. https://link.springer.com/article/10.1186/s13059-026-04099-7 , doi:10.1186/s13059-026-04099-7 “Most mutations are 1 bp expansions or contractions, with a bias toward the former” (P = 1.4e-8), in both maternal and paternal de novo mutations. So both directions occur de novo in humans, with insertions modestly favoured.</p></li>
<li><p>Mechanism at the polymerase level, two distinct routes to a 1 bp indel: Garcia-Diaz M, Kunkel TA (2006) “Mechanism of a genetic glissando: structural biology of indel mutations,” <em>Trends Biochem Sci</em> 31:206-214. https://www.cell.com/trends/biochemical-sciences/fulltext/S0968-0004(06)00058-2 , doi:10.1016/j.tibs.2006.02.004 Classic Streisinger strand slippage plus <strong>dNTP-stabilized misalignment</strong>, where an incoming dNTP pairs correctly with a downstream template base across a looped-out template base. Evidence that the dNTP-stabilized route dominates at short tracts and gives way to slippage as tract length grows: https://www.sciencedirect.com/science/article/abs/pii/S156878641500052X</p></li>
</ul>
</section>
<section id="q2.-why-does-it-hit-poly-apoly-t-harder-than-poly-gpoly-c" class="level2">
<h2 class="anchored" data-anchor-id="q2.-why-does-it-hit-poly-apoly-t-harder-than-poly-gpoly-c">Q2. Why does it hit poly-A/poly-T harder than poly-G/poly-C?</h2>
<p>The honest answer: <strong>mostly because of target abundance and tract length, not because A:T base pairs are intrinsically more slippage-prone.</strong> The intuitive 2-hydrogen-bond explanation is contradicted by the per-locus data.</p>
<ul>
<li><p>Lujan SA, Clark AB, Kunkel TA (2015) “Differences in genome-wide repeat sequence instability conferred by proofreading and mismatch repair defects,” <em>Nucleic Acids Research</em> 43:4067-4074. https://academic.oup.com/nar/article/43/8/4067/2414528 , doi:10.1093/nar/gkv271 Far more indels are seen in A/T sequence genome-wide, but that reflects the greater abundance of A/T runs. Normalized for target size, “indel rates per base pair per generation are similar and sometimes slightly higher in runs of G/C base pairs than in runs of A/T base pairs of corresponding lengths.” They note this is counterintuitive under a pure thermodynamic model and conclude slippage is limited “not only thermodynamically, but also kinetically and/or structurally.” Also from this paper: indel rates rise <strong>&gt;100,000-fold</strong> with homopolymer run length. Length is by far the dominant variable.</p></li>
<li><p>Happ et al.&nbsp;2026 (above) makes the same point in the human germline, more strongly: G/C homopolymers are under 1% of homopolymer loci but show an <strong>18-fold higher per-locus mutation rate</strong> than A/T homopolymers (rate ratio 0.056, 95% CI 0.042-0.077, P &lt; 2.2e-16). Caveat: their locus set is long homopolymers (&gt;=10 bp), and a &gt;=10 bp G/C run is an unusual sequence, so this is not a clean matched comparison across all lengths.</p></li>
</ul>
<p>So the observed poly-A/poly-T dominance in human indel spectra is largely a <strong>supply</strong> effect. The human genome is full of long A/T homopolymers, mainly the poly-A tails of Alu and L1 insertions, while G/C runs are short and rare. Combine a super-exponential length dependence with a length distribution shifted far to the right for A/T, and A/T homopolymer indels dominate the genome-wide spectrum even at equal or lower per-locus rates.</p>
<section id="structuraldynamic-arguments-that-are-still-made" class="level3">
<h3 class="anchored" data-anchor-id="structuraldynamic-arguments-that-are-still-made">Structural/dynamic arguments that are still made</h3>
<ul>
<li><p>Bacolla A, Zhu X, Chen H, Howells K, Cooper DN, Vasquez KM (2015) “Local DNA dynamics shape mutational patterns of mononucleotide repeats in human genomes,” <em>Nucleic Acids Research</em> 43:5065-5080. https://pmc.ncbi.nlm.nih.gov/articles/PMC4446427 , doi:10.1093/nar/gkv364 A-tracts and G-tracts have qualitatively different mutation profiles, not just different rates. A-tract mutations cluster at the first and last base pair of the tract and track local flexibility (peak fluctuation at the 5’-TA-3’ junction). G-tract mutations cluster internally at G2-G3 and G5, and are explained by long-range hole transfer after ionization, that is oxidative chemistry, not slippage. Indels are more abundant at flanking base pairs than within tracts, ~10-fold more so for G-tracts. This argues the two tract types have different dominant mutagenic mechanisms, which is a cleaner framing than “A/T slips more.”</p></li>
<li><p>Structural: poly(dA).poly(dT) has a narrow, deep minor groove, high propeller twist and cross-strand hydrogen bonding, and is unusually straight and rigid. G-runs instead form G-quadruplex-type secondary structure, which is actively resolved by FANCJ/DOG-1 helicase, and loss of that helicase causes deletions initiating in G/C tracts. See the C. elegans work: https://pmc.ncbi.nlm.nih.gov/articles/PMC2211496/ So G/C runs may be protected by a dedicated pathway rather than being intrinsically stable.</p></li>
<li><p>Base stacking, not hydrogen bond count, dominates sequence-dependent duplex stability, which further undercuts the naive “2 vs 3 H-bonds” story.</p></li>
</ul>
</section>
</section>
<section id="which-human-polymerases-are-involved" class="level2">
<h2 class="anchored" data-anchor-id="which-human-polymerases-are-involved">Which human polymerases are involved</h2>
<p>Humans encode roughly 15 DNA-dependent DNA polymerases, catalogued in Lange SS, Takata K, Wood RD (2011) “DNA polymerases and cancer,” <em>Nature Reviews Cancer</em> 11:96-110. https://www.nature.com/articles/nrc2998 , doi:10.1038/nrc2998 Only a handful carry out bulk synthesis.</p>
<section id="bulk-nuclear-replication-b-family" class="level3">
<h3 class="anchored" data-anchor-id="bulk-nuclear-replication-b-family">Bulk nuclear replication (B-family)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Pol</th>
<th>Gene</th>
<th>Role</th>
<th>3’-&gt;5’ proofreading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pol alpha</td>
<td><code>POLA1</code> + primase</td>
<td>RNA primer then ~20 nt of DNA, at every origin and every Okazaki fragment</td>
<td><strong>No</strong></td>
</tr>
<tr class="even">
<td>Pol delta</td>
<td><code>POLD1</code> (+ POLD2/3/4)</td>
<td>Bulk lagging strand, maturation of Pol alpha tracts, most repair resynthesis</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>Pol epsilon</td>
<td><code>POLE</code> (+ POLE2/3/4)</td>
<td>Bulk leading strand</td>
<td>Yes</td>
</tr>
</tbody>
</table>
<p>Division of labour reviewed in Burgers PMJ, Kunkel TA (2017) “Eukaryotic DNA Replication Fork,” <em>Annual Review of Biochemistry</em> 86:417-438. https://www.annualreviews.org/doi/abs/10.1146/annurev-biochem-061516-044709 , doi:10.1146/annurev-biochem-061516-044709</p>
<p><strong>Pol gamma</strong> (<code>POLG</code>) is the only polymerase that replicates mitochondrial DNA, so it is the relevant enzyme for any mtDNA homopolymer indel analysis. PrimPol and Pol theta also act on mtDNA to a minor extent.</p>
</section>
<section id="the-rest-by-job" class="level3">
<h3 class="anchored" data-anchor-id="the-rest-by-job">The rest, by job</h3>
<ul>
<li>Gap filling and base excision repair: Pol beta (<code>POLB</code>), Pol lambda (<code>POLL</code>)</li>
<li>NHEJ and V(D)J: Pol mu (<code>POLM</code>), Pol lambda, TdT (<code>DNTT</code>)</li>
<li>Translesion synthesis: Pol eta (<code>POLH</code>), Pol iota (<code>POLI</code>), Pol kappa (<code>POLK</code>), Pol zeta (<code>REV3L</code>/<code>REV7</code>), Rev1 (<code>REV1</code>), Pol nu (<code>POLN</code>)</li>
<li>Microhomology-mediated end joining: Pol theta (<code>POLQ</code>)</li>
<li>Repriming past lesions: PrimPol (<code>PRIMPOL</code>)</li>
</ul>
</section>
<section id="which-ones-matter-for-homopolymer-slippage" class="level3">
<h3 class="anchored" data-anchor-id="which-ones-matter-for-homopolymer-slippage">Which ones matter for homopolymer slippage</h3>
<p>Pol delta and Pol epsilon, and to a lesser extent Pol alpha. Pol alpha is notably error-prone and has no proofreading exonuclease, and it lays down a short DNA stretch at the start of every Okazaki fragment, which is a plausible source of some lagging-strand indels. The “Pol-dys” lines in Koh et al.&nbsp;2025 that gave exclusively 1 bp T insertions at poly-T5+ are <code>POLE</code>/<code>POLD1</code> exonuclease-domain defects, and this is the same system that motivates the proofreading-reach argument, that proofreading only rescues errors within about 5-7 bp of the active site. The translesion polymerases have far lower per-nucleotide fidelity but synthesize a tiny fraction of the genome, so they contribute little to the genome-wide indel spectrum.</p>
</section>
</section>
<section id="measured-1-bp-insertion-and-deletion-rates-for-pol-delta-and-pol-epsilon" class="level2">
<h2 class="anchored" data-anchor-id="measured-1-bp-insertion-and-deletion-rates-for-pol-delta-and-pol-epsilon">Measured 1 bp insertion and deletion rates for Pol delta and Pol epsilon</h2>
<section id="in-vitro-purified-enzyme" class="level3">
<h3 class="anchored" data-anchor-id="in-vitro-purified-enzyme">In vitro, purified enzyme</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Enzyme</th>
<th>Base substitution</th>
<th>1 bp deletion</th>
<th>1 bp insertion</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yeast Pol delta, WT, 3-subunit</td>
<td>&lt; 1.3e-5</td>
<td><strong>3.0e-4</strong> in homopolymeric runs</td>
<td>not reported as a notable class</td>
<td>Fortune 2005</td>
</tr>
<tr class="even">
<td>Yeast Pol epsilon, WT, 4-subunit</td>
<td>&lt;= 2e-5</td>
<td><strong>&lt;= 5e-7</strong></td>
<td>not reported separately</td>
<td>Shcherbakova 2003</td>
</tr>
<tr class="odd">
<td>Human Pol epsilon, exo-deficient</td>
<td>4.4e-5</td>
<td><strong>0.71e-5</strong></td>
<td><strong>0.16e-5</strong></td>
<td>Korona 2011</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Fortune JM, Pavlov YI, Welch CM, Johansson E, Burgers PMJ, Kunkel TA (2005) “Saccharomyces cerevisiae DNA polymerase delta: high fidelity for base substitutions but lower fidelity for single- and multi-base deletions,” <em>J Biol Chem</em> 280:29980-29987. doi:10.1074/jbc.M505236200 https://www.jbc.org/article/S0021-9258(20)56429-6/fulltext Wild-type Pol delta “inefficiently proofreads single nucleotide deletion mismatches in homopolymeric runs, such that the error rate is 30 single nucleotide deletions/100,000 nucleotides polymerized.” The paper’s own conclusion: “strand slippage during replication by wild type Pol delta may be a primary source of insertion and deletion mutagenesis in eukaryotic genomes.”</p></li>
<li><p>Shcherbakova PV, Pavlov YI, Chilkova O, Rogozin IB, Johansson E, Kunkel TA (2003) “Unique error signature of the four-subunit yeast DNA polymerase epsilon,” <em>J Biol Chem</em> 278:43770-43780. doi:10.1074/jbc.M306893200 https://pubmed.ncbi.nlm.nih.gov/12882968/ Wild-type Pol epsilon proofreads at least 92% of base substitution errors and <strong>at least 99% of frameshift errors</strong>.</p></li>
<li><p>Korona DA, LeCompte KG, Pursell ZF (2011) “The high fidelity and unique error signature of human DNA polymerase epsilon,” <em>Nucleic Acids Research</em> 39:1763-1773. doi:10.1093/nar/gkq1034 https://academic.oup.com/nar/article/39/5/1763/2408989 Exonuclease-deficient human Pol epsilon: deletion:insertion ratio about <strong>4.4:1</strong>. Also, human Pol epsilon was “nearly as accurate for 4-5 homonucleotide runs as it was for shorter runs or non-iterated nucleotides,” unlike other B-family polymerases.</p></li>
</ul>
<p><strong>The headline contrast:</strong> wild-type Pol delta makes single-base deletions in homopolymers at ~3e-4, roughly <strong>600-fold</strong> more often than wild-type Pol epsilon (~5e-7). Both have comparable base-substitution fidelity. The difference is entirely in frameshift proofreading, which Pol epsilon does well and Pol delta does badly. If that in vitro difference holds in vivo, homopolymer indels should be a predominantly <strong>lagging-strand</strong> phenomenon.</p>
</section>
<section id="in-vivo-yeast-whole-genomes" class="level3">
<h3 class="anchored" data-anchor-id="in-vivo-yeast-whole-genomes">In vivo, yeast whole genomes</h3>
<p>Lujan SA, Clark AB, Kunkel TA (2015) <em>NAR</em> 43:4067-4074, doi:10.1093/nar/gkv271 (Table 1, MMR-deficient strains):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Run type</th>
<th>1 bp deletions</th>
<th>1 bp insertions</th>
<th>del:ins</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A/T</td>
<td>4,686</td>
<td>424</td>
<td>~11:1</td>
</tr>
<tr class="even">
<td>G/C</td>
<td>311</td>
<td>82</td>
<td>~3.8:1</td>
</tr>
</tbody>
</table>
<p>“The number of deletions far exceeds the number of insertions, and the number of deletions and insertions is much higher for A/T as compared to G/C base pairs.” The ratio is strongly length-dependent, reaching about <strong>100-fold</strong> deletion bias at 12 bp A/T runs. Their proposed reason is thermodynamic, that forming the insertion-type misaligned intermediate requires disrupting more hydrogen bonds than the deletion-type one. Note these counts are from MMR-deficient backgrounds, so they measure the polymerase error spectrum minus whatever MMR would have caught.</p>
</section>
<section id="does-mmr-repair-1-bp-deletions-more-efficiently-than-1-bp-insertions" class="level3">
<h3 class="anchored" data-anchor-id="does-mmr-repair-1-bp-deletions-more-efficiently-than-1-bp-insertions">Does MMR repair 1 bp deletions more efficiently than 1 bp insertions?</h3>
<p>Short answer: no, and where an asymmetry exists it runs the other way for the complex that handles most single-nucleotide loops.</p>
<p>Terminology, since it is easy to invert. In the MMR literature an <strong>insertion loop</strong> is an extra nucleotide extrahelical on the <strong>primer/nascent</strong> strand, which if unrepaired becomes an insertion mutation. A <strong>deletion loop</strong> is an extra nucleotide on the <strong>template</strong> strand, which if unrepaired becomes a deletion.</p>
<ul>
<li><p>Romanova NV, Crouse GF (2013) “Different roles of eukaryotic MutS and MutL complexes in repair of small insertion and deletion loops in yeast,” <em>PLoS Genetics</em> 9:e1003920. doi:10.1371/journal.pgen.1003920 https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1003920 There <strong>is</strong> an asymmetry, and it is complex-dependent. Median repair ratios for 1-nt loops (their Table 4):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>MutS complex</th>
<th>1-nt insertion loops</th>
<th>1-nt deletion loops</th>
<th>P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MutS-alpha (Msh2-Msh6, msh3 strains)</td>
<td>190</td>
<td>73</td>
<td>0.017</td>
</tr>
<tr class="even">
<td>MutS-beta (Msh2-Msh3, msh6 strains)</td>
<td>3</td>
<td>22</td>
<td>0.029</td>
</tr>
</tbody>
</table>
<p>“MutSalpha has a consistently greater activity toward 1-nt insertion mismatches, whereas the MutSbeta activity is the reverse.” They argue the pattern likely holds in mammalian cells. Since MutS-alpha is the main complex acting on single-nucleotide loops, the net effect of MMR should be to remove <strong>insertion</strong>-type errors somewhat preferentially, which would <em>deepen</em> rather than offset the polymerase deletion bias.</p></li>
<li><p>Lujan SA, Clark AB, Kunkel TA (2015) <em>NAR</em> 43:4067-4074, doi:10.1093/nar/gkv271 At the genome scale they see no evidence of differential MMR efficiency. The deletion-to-insertion ratio is similar in MMR-proficient and MMR-deficient strains, single-base deletion rates exceed insertion rates across genotypes, and “a high deletion to insertion ratio is also observed during synthesis <em>in vitro</em> by DNA polymerases.” They attribute the bias to the polymerase step, specifically that “base-base hydrogen bonding must be disrupted for one more base pair in order to create an insertion mismatch…as compared to a deletion mismatch.”</p></li>
</ul>
<p><strong>Correction to an earlier note in this file.</strong> I had suggested that MMR might preferentially remove deletion-type intermediates, leaving an insertion-biased spectrum in MMR-proficient cells. Both papers above contradict that. Lujan et al.&nbsp;find no differential MMR efficiency at all, and Romanova and Crouse find MutS-alpha favouring insertion loops, the opposite direction.</p>
</section>
<section id="the-discordance-that-remains" class="level3">
<h3 class="anchored" data-anchor-id="the-discordance-that-remains">The discordance that remains</h3>
<p>So the insertion-biased human observations are still unexplained by differential MMR:</p>
<ul>
<li>Happ et al.&nbsp;2026 germline de novo homopolymer mutations favour expansions (P = 1.4e-8).</li>
<li>Koh et al.&nbsp;2025 polymerase-dysfunction cell lines gave <em>exclusively</em> 1 bp T insertions at poly-T5+.</li>
<li>COSMIC ID1 (insertion) is near-universal and clock-like, while ID2 (deletion) is the one that explodes in MMR deficiency.</li>
</ul>
<p>Against in vitro and yeast in vivo data that are deletion-biased at every genotype tested. Candidate explanations not yet checked here: the yeast reporter and genome assays sample much shorter homopolymers than the human loci in question, short-read alignment is known to call insertions and deletions at homopolymers with different sensitivity, and the human germline number comes from a specific long-allele locus set (&gt;=10 bp). A direct test in our data is the del:ins ratio stratified by homopolymer length in MMR-proficient versus MMR-deficient tumours, which shows whether the human insertion bias is real, length-specific, or a calling artefact. That test has now been run, see the next section.</p>
</section>
</section>
<section id="our-own-data-the-discordance-is-length-specific" class="level2">
<h2 class="anchored" data-anchor-id="our-own-data-the-discordance-is-length-specific">Our own data: the discordance is length-specific</h2>
<p>The test proposed above has now been run on the Liu et al.&nbsp;ID476 cohort. Script, augmented table and figures are in <code>~/github/zz-liu_2025_draft_release/del-vs-ins-analysis/</code>.</p>
<p>Method. Transpose the 476-channel spectra, aggregate the 342 one-base homopolymer channels across their 9 flanking contexts into per-tract-length deletion and insertion counts, and split by <code>MSIseq_MSI.H</code>. <strong>Tumours carrying a POLD1 or POLE proofreading variant in Table S9 are excluded up front</strong>, 26 of them, since polymerase proofreading deficiency is the perturbation under study and would otherwise sit inside the comparison groups. That leaves 6,952 tumours: 182 MMR-deficient (MSI-H), 6,767 MMR-proficient and 3 unknown. The excluded tumours are heavily hypermutated (median 18,070 indels against 680 for those kept) and 20 of the 26 are MSI-H, so the exclusion bites hardest on the MSI-H pooled counts. Panel Rn compares Del(base):Rn with Ins(base):Rn, both meaning a tract of n bases existed <strong>before</strong> the event, so the two channels describe the same substrate, which is confirmed by the ICAMS classifier: <code>R</code> is the tract length before the mutation for insertions as well as deletions (see the caveats below). No indel-burden filter is applied, because a 4,000-indel cutoff would remove 200 of the 202 MSI-H tumours.</p>
<section id="pooled-insertions-deletions-by-tract-length" class="level3">
<h3 class="anchored" data-anchor-id="pooled-insertions-deletions-by-tract-length">Pooled insertions / deletions by tract length</h3>
<p>Values above 1 mean insertions exceed deletions. Pooled across tumours rather than a median of per-tumour ratios, since most tumours are zero in most channels.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Tract</th>
<th>R1</th>
<th>R2</th>
<th>R3</th>
<th>R4</th>
<th>R5</th>
<th>R6</th>
<th>R7</th>
<th>R8</th>
<th>R9+</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>poly-T, MMR proficient</td>
<td>0.59</td>
<td>0.46</td>
<td>0.45</td>
<td>0.31</td>
<td>0.83</td>
<td><strong>2.29</strong></td>
<td><strong>1.79</strong></td>
<td><strong>1.64</strong></td>
<td>0.94</td>
</tr>
<tr class="even">
<td>poly-T, MSI-H</td>
<td>0.45</td>
<td>1.53</td>
<td>0.68</td>
<td>0.39</td>
<td>0.32</td>
<td>0.57</td>
<td>0.32</td>
<td>0.25</td>
<td>0.14</td>
</tr>
<tr class="odd">
<td>poly-C, MMR proficient</td>
<td>0.10</td>
<td>0.07</td>
<td>0.10</td>
<td>0.22</td>
<td>0.28</td>
<td>0.56</td>
<td><strong>2.17</strong></td>
<td><strong>1.78</strong></td>
<td>0.45</td>
</tr>
<tr class="even">
<td>poly-C, MSI-H</td>
<td>0.10</td>
<td>0.13</td>
<td>0.31</td>
<td>1.06</td>
<td>0.26</td>
<td>0.26</td>
<td>0.52</td>
<td>0.47</td>
<td>0.19</td>
</tr>
</tbody>
</table>
</section>
<section id="coarse-bins-at-the-koh-et-al.-2025-thresholds" class="level3">
<h3 class="anchored" data-anchor-id="coarse-bins-at-the-koh-et-al.-2025-thresholds">Coarse bins at the Koh et al.&nbsp;2025 thresholds</h3>
<p>Koh et al.&nbsp;report 1 bp T deletions at poly-T6+ in MMR-deficient lines and 1 bp T insertions at poly-T5+ in polymerase-dysfunction lines, so these two bins are at different tract lengths and this ratio is <strong>not</strong> a same-substrate comparison.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>deletions from 6+</th>
<th>insertions into 5+</th>
<th>ins/del</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>poly-T, MMR proficient</td>
<td>806,980</td>
<td>1,304,237</td>
<td><strong>1.62</strong></td>
</tr>
<tr class="even">
<td>poly-T, MSI-H</td>
<td>6,687,129</td>
<td>1,772,878</td>
<td><strong>0.27</strong></td>
</tr>
<tr class="odd">
<td>poly-C, MMR proficient</td>
<td>49,249</td>
<td>65,857</td>
<td><strong>1.34</strong></td>
</tr>
<tr class="even">
<td>poly-C, MSI-H</td>
<td>371,072</td>
<td>171,521</td>
<td><strong>0.46</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="what-this-shows" class="level3">
<h3 class="anchored" data-anchor-id="what-this-shows">What this shows</h3>
<ol type="1">
<li><p><strong>The two MMR states diverge with tract length, in opposite directions.</strong> In MMR-proficient tumours the ratio climbs with length and crosses 1 at poly-T6, peaking near 2.3. In MSI-H tumours it falls monotonically past R2, reaching 0.15 at R9+, so deletions outnumber insertions about 7:1 at long tracts. On the coarse bins that is a 6.1-fold swing in ins:del between MMR states for poly-T, and 2.9-fold for poly-C.</p></li>
<li><p><strong>This reproduces Koh et al.&nbsp;2025 in an independent cohort</strong>, from raw channel counts with no signature extraction. Their polymerase-dysfunction insertions at poly-T5+ and MMR-deficient deletions at poly-T6+ appear here as an MMR-proficient insertion excess starting at exactly poly-T6 and an MSI-H deletion excess growing over the same range. It is ID1 versus ID2 falling out of the counts directly.</p></li>
<li><p><strong>The human insertion bias is length-specific, not global.</strong> At short tracts (R1 to R4) deletions dominate in both MMR groups, which agrees with the yeast and in vitro measurements. The insertion excess appears only at R6 to R8. That partly reconciles the discordance above: the yeast reporter and genome assays sample short homopolymers, exactly the range where our human data agree with them, so the two bodies of work may not actually conflict.</p></li>
</ol>
</section>
<section id="where-insdel_n_beta-sits-on-this-axis" class="level3">
<h3 class="anchored" data-anchor-id="where-insdel_n_beta-sits-on-this-axis">Where InsDel_N_beta sits on this axis</h3>
<p>The ID89 signature <code>InsDel_N_beta</code> turns out to be the interesting one for the slippage question. Full analysis with code in <code>~/github/zz-liu_2025_draft_release/del-vs-ins-analysis/n_beta_ins_del.qmd</code>.</p>
<p><strong>N_beta is the balanced long-poly-T signature.</strong> Taking the insertion and deletion content of each ID89 signature profile:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Signature</th>
<th>% insertions</th>
<th>% deletions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>InsDel1a</td>
<td>93.7</td>
<td>6.3</td>
</tr>
<tr class="even">
<td>InsDel2a</td>
<td>25.2</td>
<td>74.8</td>
</tr>
<tr class="odd">
<td><strong>InsDel_N_beta</strong></td>
<td><strong>42.8</strong></td>
<td><strong>57.2</strong></td>
</tr>
</tbody>
</table>
<p>1a is essentially pure insertion and 2a mostly deletion, the two directional extremes. N_beta sits between them, and its top channels interleave both directions at the same long tracts: <code>A[Del(T):R(8,)]A</code>, <code>A[Del(T):R(5,7)]A</code>, <code>A[Ins(T):R(5,7)]C</code>, <code>A[Ins(T):R(8,)]A</code>. That is what an undirected slippage process should look like, a tract of 8 T’s going to 7 about as often as it goes to 9.</p>
<p><strong>Group ratios follow from mixing.</strong> Restricting to MMR-proficient tumours, so that burden and MSI status do not drive the contrast, and using the coarse bins (ins into 5+ over del from 6+):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th>n</th>
<th>median indel burden</th>
<th>poly-T ins/del</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>no N_beta</td>
<td>4,141</td>
<td>494</td>
<td>3.06</td>
</tr>
<tr class="even">
<td>N_beta + 1 family only</td>
<td>1,316</td>
<td>964</td>
<td>1.81</td>
</tr>
<tr class="odd">
<td>N_beta alone</td>
<td>1,189</td>
<td>1,092</td>
<td>1.00</td>
</tr>
<tr class="even">
<td>N_beta + 2 family only</td>
<td>121</td>
<td>1,848</td>
<td>0.56</td>
</tr>
</tbody>
</table>
<p>The third row is the consistency check. Tumours carrying N_beta and neither directional family land at 1.00, exactly what a 43/57 signature predicts. Adding the insertion family pushes to 1.82, adding the deletion family pulls to 0.56.</p>
<p><strong>N_beta is MMR proficient.</strong> Only 9 of 2,635 N_beta tumours are MSI-H (0.34%), against 4.0% of tumours without it.</p>
<p><strong>Co-occurrence is lopsided but that is not the interesting part.</strong> Of the 2,635 N_beta tumours, 1,192 carry neither directional family, 1,317 carry the 1 family only, 124 the 2 family only, and just 2 carry both. The 1 and 2 families are near mutually exclusive. The 10:1 skew toward the 1 family mostly reflects how common that family is: among the 4,141 MSS tumours <strong>without</strong> N_beta, 3,095 carry the 1 family only, 91 the 2 family only, 62 both, and 893 neither.</p>
<p><strong>Why this matters here.</strong> The report above frames the problem as a conflict between deletion-biased enzymology and insertion-biased human data. N_beta suggests the human data contain a component that is neither. If N_beta is the underlying slippage process and 1a and 2a are what happens when something biases it, then the quantity to explain is not “why are human indels insertion-biased” but “what tips a balanced process one way or the other”. MMR status is one such tipping factor and is visible in the tables above, but N_beta tumours are almost all MMR proficient, so it cannot be the only one.</p>
</section>
<section id="the-1-family-broken-out-by-subtype" class="level3">
<h3 class="anchored" data-anchor-id="the-1-family-broken-out-by-subtype">The 1 family broken out by subtype</h3>
<p>Among MSS tumours the three 1-family signatures are close to mutually exclusive: 3,780 carry <code>InsDel1a</code> only, 552 <code>InsDel1c</code> only, 138 <code>InsDel1b</code> only, 3 carry more than one, and 2,294 carry none. Broken out that way, on the coarse bins:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th>n</th>
<th>% with N_beta</th>
<th>median burden</th>
<th>poly-T ins/del</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>InsDel1a</td>
<td>3,780</td>
<td>31.4</td>
<td>647</td>
<td><strong>2.39</strong></td>
</tr>
<tr class="even">
<td>InsDel1b</td>
<td>138</td>
<td>11.6</td>
<td>207</td>
<td><strong>2.36</strong></td>
</tr>
<tr class="odd">
<td>InsDel1c</td>
<td>552</td>
<td>20.7</td>
<td>353</td>
<td><strong>2.38</strong></td>
</tr>
<tr class="even">
<td>no 1 family</td>
<td>2,294</td>
<td>57.1</td>
<td>870</td>
<td>0.94</td>
</tr>
</tbody>
</table>
<p>The three are indistinguishable, 2.39 / 2.36 / 2.38, across a 27-fold range in tumour count. That holds even though <code>InsDel1b</code> carries noticeably more deletions than the other two (21.8% against 6.3% for 1a and 7.4% for 1c). Whatever separates 1a, 1b and 1c from each other, it is not the insertion/deletion balance at long poly-T tracts, which is consistent with all three being variants of the same directional process.</p>
<p>Splitting each subtype by whether the tumour also carries N_beta reproduces the dilution effect within every one of them:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th>without N_beta</th>
<th>with N_beta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>InsDel1a</td>
<td>3.81 (n = 2,594)</td>
<td>1.83 (n = 1,186)</td>
</tr>
<tr class="even">
<td>InsDel1b</td>
<td>2.97 (n = 122)</td>
<td>1.63 (n = 16)</td>
</tr>
<tr class="odd">
<td>InsDel1c</td>
<td>3.78 (n = 438)</td>
<td>1.62 (n = 114)</td>
</tr>
<tr class="even">
<td>no 1 family</td>
<td>1.21 (n = 984)</td>
<td>0.91 (n = 1,310)</td>
</tr>
</tbody>
</table>
<p>Adding N_beta roughly halves the ratio in each case, which is what mixing in a 57% deletion signature should do.</p>
</section>
<section id="caveats" class="level3">
<h3 class="anchored" data-anchor-id="caveats">Caveats</h3>
<ul>
<li><p><strong>The R9+ drop, checked.</strong> The ratio falls back below 1 at R9+ in both MMR-proficient rows. Two candidate explanations were tested and one survives.</p>
<p><em>Not a binning artefact.</em> The concern was that <code>Del:R(9,)</code> and <code>Ins:R(9,)</code> might pool different tract-length distributions. They do not. In ICAMS <code>categorize_1_justified_indel()</code> the repeat count <code>R</code> is the tract length <strong>before</strong> the mutation for insertions as well as deletions, the insertion path explicitly subtracting one because the context it matches against is post-insertion:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>indel_str_count_in_ref <span class="ot">=</span> <span class="fu">nchar</span>(all_repeated_seq) <span class="sc">/</span> ins_or_del_seq_len</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (ins_or_del <span class="sc">==</span> <span class="st">"i"</span>) {</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  indel_str_count_in_ref <span class="ot">=</span> indel_str_count_in_ref <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># x_context was the sequence after the insertion. We want</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># indel_str_count_in_ref to reflect the repeat count prior to the insertion</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>So both channels draw on the same set of genomic tracts of length &gt;= 9 and the bins are symmetric.</p>
<p><em>Not pipeline-specific.</em> Splitting the MMR-proficient tumours by cohort gives nearly identical curves for HMF (n = 4,034) and PCAWG (n = 2,733), poly-T ins/del:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Cohort</th>
<th>R4</th>
<th>R5</th>
<th>R6</th>
<th>R7</th>
<th>R8</th>
<th>R9+</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HMF</td>
<td>0.315</td>
<td>0.834</td>
<td>2.261</td>
<td>1.754</td>
<td>1.608</td>
<td>0.940</td>
</tr>
<tr class="even">
<td>PCAWG</td>
<td>0.309</td>
<td>0.810</td>
<td>2.357</td>
<td>1.869</td>
<td>1.763</td>
<td>0.962</td>
</tr>
</tbody>
</table>
<p>Two cohorts with different sequencing and calling pipelines agree to within about 3% at every bin, including the drop. The MSI-H split behaves the same way.</p>
<p><em>What is left.</em> Either the ins/del ratio genuinely declines above tract length 9, making the MMR-proficient curve unimodal with a peak at poly-T6, or short-read sequencing loses 1 bp insertions faster than 1 bp deletions once the tract exceeds what a read can span. The cohort check cannot separate these, since HMF and PCAWG are both Illumina short-read and would share any technology-wide limitation. That is the same <code>k</code> problem as below, concentrated at the longest tracts, and it needs long-read or duplex data to settle.</p></li>
<li><p>poly-C at R7 and R8 rests on small counts.</p></li>
<li><p><strong>Calling sensitivity, and which of our claims it threatens.</strong> Short-read calling need not detect 1 bp insertions and 1 bp deletions at long homopolymers equally well. Write <code>k</code> for the ratio of insertion sensitivity to deletion sensitivity. Every ins/del value in the tables above is then the true ratio multiplied by <code>k</code>.</p>
<p>The <strong>between-group comparison survives any value of <code>k</code>.</strong> Both groups pass through the same pipeline, so <code>k</code> cancels when the two ratios are divided: 1.62 / 0.27 = 6.1 for poly-T regardless of <code>k</code>. The 6.1-fold swing between MMR states is the robust result.</p>
<p>The <strong>absolute position of the curve does not survive.</strong> “Insertions exceed deletions at poly-T6 in MMR-proficient tumours” compares an observed ratio against the fixed threshold of 1, and <code>k</code> does not cancel against a constant. At k = 0.5 the true poly-T6 ratio would be 4.6 rather than 2.29, at k = 2 it would be 1.15, and the tract length at which the curve crosses 1 slides accordingly. So the crossing point landing at exactly poly-T6, which is what makes the agreement with Koh et al.&nbsp;2025 look tidy, is the weaker of the two claims.</p>
<p>Two limits on this argument itself. We have not established which direction <code>k</code> runs, only that there is no reason for it to be 1. And “internally controlled” assumes calling behaves the same way in both groups, which is imperfect here, since MSI-H tumours carry roughly an order of magnitude more indels and may pass through burden-dependent filters differently. Settling this would need a truth set, for example long-read or duplex-sequenced homopolymer calls in a few samples from each group.</p></li>
</ul>
</section>
</section>
<section id="bottom-line" class="level2">
<h2 class="anchored" data-anchor-id="bottom-line">Bottom line</h2>
<ol type="1">
<li>Both +T and -T at poly-T are real and mechanistically distinguished: ID1 (nascent strand slippage, insertion) vs ID2 (template strand slippage, deletion), with experimental separation in Koh et al.&nbsp;2025 and de novo germline confirmation in Happ et al.&nbsp;2026.</li>
<li>There is <strong>no good evidence that A:T base pairs slip more readily than G:C at matched tract length.</strong> The genome-wide poly-A/poly-T dominance is driven by tract length and tract abundance. Anyone claiming an intrinsic A/T slippage preference should be pointed at Lujan et al.&nbsp;2015 and Happ et al.&nbsp;2026.</li>
<li><strong>MMR does not preferentially repair one direction.</strong> Lujan et al.&nbsp;2015 find the del:ins ratio is unchanged between MMR-proficient and MMR-deficient strains, and Romanova &amp; Crouse 2013 find MutS-alpha favours insertion loops if anything.</li>
<li><strong>In our cohort the ins:del ratio depends on tract length and MMR state together.</strong> Deletions dominate at short tracts in both MMR states, matching the yeast and in vitro data. Insertions overtake deletions only at poly-T6 to poly-T8 and only in MMR-proficient tumours. So the apparent conflict between the human insertion bias and the deletion-biased enzymology is largely a matter of which tract lengths each body of work samples.</li>
</ol>
</section>
<section id="related-material-in-this-folder" class="level2">
<h2 class="anchored" data-anchor-id="related-material-in-this-folder">Related material in this folder</h2>
<ul>
<li>The indel signature classification paper (<code>README.md</code>, <code>long-abst.md</code>, <code>abstract-150.md</code>). Relevant to that work: the ID1/ID2 nascent-vs-template split, the tract-length dependence of insertion vs deletion excess (Koh et al.&nbsp;2025), and the point that A/T dominance is a target-abundance effect, which bears on opportunity normalization for any new indel classification.</li>
<li><a href="comparison-with-koh-2025.md"><code>comparison-with-koh-2025.md</code></a></li>
<li>The cohort analysis behind the “Our own data” section lives outside this repo, in <code>~/github/zz-liu_2025_draft_release/del-vs-ins-analysis/</code> (script, augmented 6,952 x 524 table, the list of POLD1/POLE tumours excluded, a 4-page PDF of the scatters and ratio summary, and <code>n_beta_ins_del.qmd</code> with the code for every table).</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>